language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/github.com/c4pt0r/ninep"
  - go get -v -t -d github.com/c4pt0r/ninep/...
script:
  - go test github.com/c4pt0r/ninep/...
